-- ═══════════════════════════════════════════════════════════════════════════
-- FASE 3b — ACERTO mensal por parceiro
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Correr DEPOIS de fase3_despesas.sql. Só cria tabelas novas.
--
-- Fórmula do acerto (a validar): para um parceiro e um mês —
--   Receita  = renda COBRADA (valor pago) das cobranças dos veículos do
--              parceiro cujo vencimento cai no mês.
--   Comissão = por veículo, receita × comissão% do veículo (override do veículo
--              ou a % base do proprietário). É a receita da GoScooters.
--   Despesas = despesas imputadas ao PROPRIETÁRIO, dos seus veículos, no mês.
--   Líquido  = Receita − Comissão − Despesas  (o que se transfere ao parceiro).
--
-- Ao FECHAR, cada linha é CONGELADA em acerto_linha: o extrato de um mês nunca
-- muda, mesmo que se corrija uma fatura antiga — a falha exacta do Sheets.

